//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS2List
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Part_OS2Entities : DbContext
    {
        public DB_Part_OS2Entities()
            : base("name=DB_Part_OS2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Kust_List> tbl_Kust_List { get; set; }
        public DbSet<tbl_Modul_Name> tbl_Modul_Name { get; set; }
        public DbSet<tbl_ORM> tbl_ORM { get; set; }
        public DbSet<tbl_ORM_List> tbl_ORM_List { get; set; }
        public DbSet<tbl_Movement_Details> tbl_Movement_Details { get; set; }
        public DbSet<tbl_Movement_List> tbl_Movement_List { get; set; }
    }
}
