//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS2List
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTTNEntities : DbContext
    {
        public DBTTNEntities()
            : base("name=DBTTNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Current_Movement> tbl_Current_Movement { get; set; }
        public DbSet<tbl_Kadrovii_Sostav> tbl_Kadrovii_Sostav { get; set; }
        public DbSet<tbl_Kadrovii_Sostav_par> tbl_Kadrovii_Sostav_par { get; set; }
        public DbSet<tbl_Mestorojdenie> tbl_Mestorojdenie { get; set; }
        public DbSet<tbl_Modul_Name> tbl_Modul_Name { get; set; }
        public DbSet<tbl_Movement_History> tbl_Movement_History { get; set; }
        public DbSet<tbl_Movement_History_Details> tbl_Movement_History_Details { get; set; }
        public DbSet<tbl_ORM> tbl_ORM { get; set; }
        public DbSet<tbl_Spiski> tbl_Spiski { get; set; }
    }
}
