//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS2List
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Movement_History_Details
    {
        public int ID_Movement_History_Details { get; set; }
        public Nullable<int> Kod_Movement_History { get; set; }
        public Nullable<int> Kod_Modul_Name { get; set; }
        public string Modul_Name_IF_Definition_Not_Exist_In_Dictionary { get; set; }
        public Nullable<int> Count_Modul { get; set; }
        public Nullable<float> Weight_Modul { get; set; }
        public string Kod_Way_To_Get_Weight { get; set; }
        public Nullable<int> Kod_Package { get; set; }
        public Nullable<int> Kod_Ed_Izmer { get; set; }
        public string Zavod_Invent_Number { get; set; }
    }
}
