//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS2List
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ORM
    {
        public string Short_Name_ORM { get; set; }
        public string Full_Name_ORM { get; set; }
        public int ID_ORM { get; set; }
        public Nullable<int> Kod_Zech_ORM { get; set; }
        public string Phone_ORM { get; set; }
    }
}
