//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS2List
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kadrovii_Sostav
    {
        public string Tab_N_KS { get; set; }
        public string Familiya_KS { get; set; }
        public string Imya_KS { get; set; }
        public string Otchestvo_KS { get; set; }
        public string Dolgnost_KS { get; set; }
        public int ID_KS { get; set; }
        public Nullable<int> Kod_ORM_KS { get; set; }
        public string Comment_KS { get; set; }
        public Nullable<int> Priority_Doljnost_KS { get; set; }
    }
}
