//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS2List
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Movement_Details
    {
        public int ID_Mov_Det { get; set; }
        public int Code_Movement_List { get; set; }
        public string Modul_Movement { get; set; }
        public Nullable<int> Modul_count { get; set; }
        public string Weight { get; set; }
    }
}
