//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS2List
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Modul_Name
    {
        public int ID_Modul_Name { get; set; }
        public string Short_Name_Modul_Name { get; set; }
        public string Full_Name_Modul_Name { get; set; }
        public string Catalog_Nomer_Modul_Name { get; set; }
        public string Class_Modul_Name { get; set; }
        public string Comment_Modul_Name { get; set; }
        public Nullable<int> Weight_Modul_Name { get; set; }
        public string Way_To_Find_Weight { get; set; }
        public byte[] Image_Path { get; set; }
    }
}
