//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS2List
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kadrovii_Sostav_par
    {
        public int ID_KS_Par { get; set; }
        public Nullable<int> Kod_KS_Par { get; set; }
        public string Parametr_Name_KS_Par { get; set; }
        public string Parametr_Text_KS_Par { get; set; }
        public string Parametr_Comment_KS_Par { get; set; }
    }
}
