//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS2List
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Movement_List
    {
        public int ID_Movement { get; set; }
        public string Date { get; set; }
        public string Driver { get; set; }
        public string Driver_Movement_List_ID { get; set; }
        public string Sender { get; set; }
        public string Kust_Name { get; set; }
        public string Kust_Number { get; set; }
        public string Well_Number { get; set; }
        public string ITS_PartNumber_ORM { get; set; }
    }
}
