//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS2List
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Current_Movement
    {
        public int ID_Movement { get; set; }
        public string Modul_Name { get; set; }
        public string Zavod_Number { get; set; }
        public Nullable<int> Count { get; set; }
        public string Package { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Way_To_Get_Weight { get; set; }
        public string Ed_Izmer { get; set; }
    }
}
